### ISSUE TITLE
scrypt errors cause deploy to fail

### ISSUE THREAD

**Issue by techbubble** [loomnetwork/loom-truffle-provider#12]
Due to scrypt errors, it doesn't get installed properly and the deployment does not work. This is the case on both Mac and Windows.

`$ node scripts/gen-loom-key.js extdev_private_key
✨  Done in 1.21s.
nik@Pascal truffle-dappchain-example % yarn deploy:extdev
yarn run v1.22.4
$ truffle deploy --network extdev_plasma_us1
Error: Cannot find module './build/Release/scrypt'
Require stack:
- /Users/nik/Developer/truffle-dappchain-example/node_modules/scrypt/index.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/scrypt.js/node.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/web3-eth-accounts/src/index.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/web3-eth/src/index.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/web3/src/index.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/loom-js/dist/solidity-helpers.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/loom-js/dist/middleware/signed-eth-tx-middleware.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/loom-js/dist/middleware/index.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/loom-js/dist/helpers.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/loom-js/dist/client.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/loom-js/dist/index.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/dist/index.js
- /Users/nik/Developer/truffle-dappchain-example/truffle-config.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/original-require/index.js
- /Users/nik/Developer/truffle-dappchain-example/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nik/Developer/truffle-dappchain-example/node_modules/scrypt/index.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/scrypt.js/node.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/web3-eth-accounts/src/index.js:35:16)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/nik/Developer/truffle-dappchain-example/node_modules/loom-truffle-provider/node_modules/web3-eth/src/index.js:36:16)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
Truffle v5.0.1 (core: 5.0.1)
Node v13.6.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by joshuaebowling** [comment]
@techbubble 
I was able to get it to work by running node 10.24.1
scrypt's last update was over 5 years ago. 
After spending all day trying to figure the best way to resolve, this is what I settled on.

**Comment by enlight** [comment]
Node v13 is no longer maintained, try upgrading to Node v14 LTS. Then delete `node_modules` in the `truffle-dappchain-example` directory and run `yarn install` again. If you're still having issue see if the workaround mentioned here works for you https://github.com/loomnetwork/loom-js/issues/345

**Comment by enlight** [comment]
The `scrypt` installation issues should be resolved in `loom-truffle-provider@0.15.0`.
